# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_published'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Uri slug', unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
